[package]
name = "cosmic-applet-firewall"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["process", "time"] }

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic.git"
default-features = false
features = ["applet", "applet-token", "tokio"]
